Refonte de la gestion réseau côté serveur (Communication/CommunicationThread/Master)
benjaminchazelle/DNAnalyzer pull request #23
Opened 2017-05-20 22:48 UTC by benjaminchazelle

2017-05-20 23:14 UTC, Egaro555 commented
pas rebase et pas build alors ... alors ... bouyave!

2017-05-21 01:12 UTC, Egaro555 commented on DNAnalyzer/DNAnalyzerServer/Master.cpp
> +		response += maladie + "\r\n";
maladieNom plutôt que maladie? (oui j'ai rien trouvez d'autre a dir XD)

2017-05-21 01:13 UTC, Egaro555 approved these changes

2017-05-21 14:10 UTC, Egaro555 requested changes

2017-05-21 14:10 UTC, Egaro555 commented on DNAnalyzer/DNAnalyzerServer/Master.cpp
> +		response += " ";
response += "\r\n";

2017-05-23 08:29 UTC, Egaro555 approved these changes

2017-05-24 07:19 UTC, smato13 approved these changes

2017-05-24 07:19 UTC, merged